//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PM_Dashboard.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Task List Documentation.
        /// </summary>
        public static string Asset__UpdateTaskListDoc {
            get {
                return ResourceManager.GetString("Asset__UpdateTaskListDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Interview Data.
        /// </summary>
        public static string Asset_AnalyzeInterview {
            get {
                return ResourceManager.GetString("Asset_AnalyzeInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Previews.
        /// </summary>
        public static string Asset_DesignPreviews {
            get {
                return ResourceManager.GetString("Asset_DesignPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Specs.
        /// </summary>
        public static string Asset_DesignSpecs {
            get {
                return ResourceManager.GetString("Asset_DesignSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Bugs.
        /// </summary>
        public static string Asset_FixBugs {
            get {
                return ResourceManager.GetString("Asset_FixBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather and Prepare Initial Design elements.
        /// </summary>
        public static string Asset_GatherDesign {
            get {
                return ResourceManager.GetString("Asset_GatherDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Documentation.
        /// </summary>
        public static string Asset_InteractionDoc {
            get {
                return ResourceManager.GetString("Asset_InteractionDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Adjustments to Prototype.
        /// </summary>
        public static string Asset_MakeAdjustments {
            get {
                return ResourceManager.GetString("Asset_MakeAdjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Notes.
        /// </summary>
        public static string Asset_MeetingNotes {
            get {
                return ResourceManager.GetString("Asset_MeetingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Interview Questions.
        /// </summary>
        public static string Asset_PrepInterviewQ {
            get {
                return ResourceManager.GetString("Asset_PrepInterviewQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototyping.
        /// </summary>
        public static string Asset_Prototyping {
            get {
                return ResourceManager.GetString("Asset_Prototyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Updated Link of Project.
        /// </summary>
        public static string Asset_ProvideUpdateLink {
            get {
                return ResourceManager.GetString("Asset_ProvideUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Interviews.
        /// </summary>
        public static string Asset_RecordInterviews {
            get {
                return ResourceManager.GetString("Asset_RecordInterviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Notes.
        /// </summary>
        public static string Asset_ResearchNotes {
            get {
                return ResourceManager.GetString("Asset_ResearchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Development Link to Project Manageer.
        /// </summary>
        public static string Asset_SendDevLink {
            get {
                return ResourceManager.GetString("Asset_SendDevLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Bug Report.
        /// </summary>
        public static string Asset_UpdateBugReport {
            get {
                return ResourceManager.GetString("Asset_UpdateBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Feedback from User Tests.
        /// </summary>
        public static string Asset_UserFeedbackDoc {
            get {
                return ResourceManager.GetString("Asset_UserFeedbackDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Test for Bugs.
        /// </summary>
        public static string Asset_UserTestBugs {
            get {
                return ResourceManager.GetString("Asset_UserTestBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe sketches.
        /// </summary>
        public static string Asset_WireframeSketches {
            get {
                return ResourceManager.GetString("Asset_WireframeSketches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Adjustments to Wireframe.
        /// </summary>
        public static string Assets_MakeAdjustmentsWireframe {
            get {
                return ResourceManager.GetString("Assets_MakeAdjustmentsWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Resources.
        /// </summary>
        public static string AssignedResources {
            get {
                return ResourceManager.GetString("AssignedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string AssignedResources_Chart_Hrs {
            get {
                return ResourceManager.GetString("AssignedResources_Chart_Hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs available.
        /// </summary>
        public static string AssignedResources_HrsAvailable {
            get {
                return ResourceManager.GetString("AssignedResources_HrsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs other.
        /// </summary>
        public static string AssignedResources_HrsOther {
            get {
                return ResourceManager.GetString("AssignedResources_HrsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs this task.
        /// </summary>
        public static string AssignedResources_HrsTask {
            get {
                return ResourceManager.GetString("AssignedResources_HrsTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task #.
        /// </summary>
        public static string AssignedResources_Task {
            get {
                return ResourceManager.GetString("AssignedResources_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but no one has been assigned to this task..
        /// </summary>
        public static string AssignedResources_Warning {
            get {
                return ResourceManager.GetString("AssignedResources_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baseline budget.
        /// </summary>
        public static string Details_BaselineBudget {
            get {
                return ResourceManager.GetString("Details_BaselineBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours/planned.
        /// </summary>
        public static string Details_HoursPlanned {
            get {
                return ResourceManager.GetString("Details_HoursPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned end date.
        /// </summary>
        public static string Details_PlannedEndDate {
            get {
                return ResourceManager.GetString("Details_PlannedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projected budget.
        /// </summary>
        public static string Details_ProjectedBudget {
            get {
                return ResourceManager.GetString("Details_ProjectedBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projected end date.
        /// </summary>
        public static string Details_ProjectedEndDate {
            get {
                return ResourceManager.GetString("Details_ProjectedEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task progress.
        /// </summary>
        public static string Details_TaskProgress {
            get {
                return ResourceManager.GetString("Details_TaskProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Unfortuantely, you are using an &lt;b&gt;outdated&lt;/b&gt; browser and some element for this app are not supported. Please &lt;a href=&quot;http://browsehappy.com/&quot; class=&quot;animate-decor-disappear&quot;&gt;upgrade your browser&lt;/a&gt; to view.&lt;/span&gt;.
        /// </summary>
        public static string IEAlert_Msg {
            get {
                return ResourceManager.GetString("IEAlert_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string Nav_CurrentProjects {
            get {
                return ResourceManager.GetString("Nav_CurrentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting.
        /// </summary>
        public static string Nav_Starting {
            get {
                return ResourceManager.GetString("Nav_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Nav_Today {
            get {
                return ResourceManager.GetString("Nav_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upcoming.
        /// </summary>
        public static string Nav_UpcomingProjects {
            get {
                return ResourceManager.GetString("Nav_UpcomingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string Nav_UserDiscipline {
            get {
                return ResourceManager.GetString("Nav_UserDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string Overview_CurrentLabel {
            get {
                return ResourceManager.GetString("Overview_CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Hours vs. Planned Hours.
        /// </summary>
        public static string Overview_Title {
            get {
                return ResourceManager.GetString("Overview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 person limit per project.
        /// </summary>
        public static string Overview_Warning {
            get {
                return ResourceManager.GetString("Overview_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over allocation.
        /// </summary>
        public static string OverviewLegend_OverAllocated {
            get {
                return ResourceManager.GetString("OverviewLegend_OverAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over planned hours.
        /// </summary>
        public static string OverviewLegend_OverPlanned {
            get {
                return ResourceManager.GetString("OverviewLegend_OverPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planned.
        /// </summary>
        public static string OverviewLegend_Planned {
            get {
                return ResourceManager.GetString("OverviewLegend_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worked.
        /// </summary>
        public static string OverviewLegend_Worked {
            get {
                return ResourceManager.GetString("OverviewLegend_Worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource has more hours planned than available.
        /// </summary>
        public static string OverviewLegendHelp_OverAllocatedDesc {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverAllocatedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource has more hours planned than available and is over 40 hrs.
        /// </summary>
        public static string OverviewLegendHelp_OverAllocatedMoreDesc {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverAllocatedMoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Allocated More Than 40 hrs.
        /// </summary>
        public static string OverviewLegendHelp_OverAllocatedMoreTitle {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverAllocatedMoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Allocated.
        /// </summary>
        public static string OverviewLegendHelp_OverAllocatedTitle {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverAllocatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource has worked more than planned.
        /// </summary>
        public static string OverviewLegendHelp_OverPlannedDesc {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverPlannedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource has worked mored than planned and is over 40 hrs.
        /// </summary>
        public static string OverviewLegendHelp_OverPlannedMoreDesc {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverPlannedMoreDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Planned hrs more than 40 hrs.
        /// </summary>
        public static string OverviewLegendHelp_OverPlannedMoreTitle {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverPlannedMoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Planned hrs.
        /// </summary>
        public static string OverviewLegendHelp_OverPlannedTitle {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_OverPlannedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Read the Charts.
        /// </summary>
        public static string OverviewLegendHelp_Title {
            get {
                return ResourceManager.GetString("OverviewLegendHelp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proj#.
        /// </summary>
        public static string PM_Headline_Proj {
            get {
                return ResourceManager.GetString("PM_Headline_Proj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectPlanner.
        /// </summary>
        public static string PMHeadline_Title {
            get {
                return ResourceManager.GetString("PMHeadline_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Tasks.
        /// </summary>
        public static string ProjectTasks {
            get {
                return ResourceManager.GetString("ProjectTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string ProjectTasks_Hours {
            get {
                return ResourceManager.GetString("ProjectTasks_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string ProjectTasks_Hrs {
            get {
                return ResourceManager.GetString("ProjectTasks_Hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected End.
        /// </summary>
        public static string ProjectTasks_ProjectedEnd {
            get {
                return ResourceManager.GetString("ProjectTasks_ProjectedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view file.
        /// </summary>
        public static string ProjectTasks_ViewFile {
            get {
                return ResourceManager.GetString("ProjectTasks_ViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are no tasks available during the selected time frame..
        /// </summary>
        public static string ProjectTasks_Warning {
            get {
                return ResourceManager.GetString("ProjectTasks_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation of Interactions.
        /// </summary>
        public static string Task_AnnotationInteractions {
            get {
                return ResourceManager.GetString("Task_AnnotationInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-end Development.
        /// </summary>
        public static string Task_BackendDev {
            get {
                return ResourceManager.GetString("Task_BackendDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back-end Development II.
        /// </summary>
        public static string Task_BackendDevII {
            get {
                return ResourceManager.GetString("Task_BackendDevII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Research.
        /// </summary>
        public static string Task_DesignResearch {
            get {
                return ResourceManager.GetString("Task_DesignResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Task_Dev {
            get {
                return ResourceManager.GetString("Task_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development II.
        /// </summary>
        public static string Task_DevII {
            get {
                return ResourceManager.GetString("Task_DevII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development III.
        /// </summary>
        public static string Task_DevIII {
            get {
                return ResourceManager.GetString("Task_DevIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Research.
        /// </summary>
        public static string Task_DevResearch {
            get {
                return ResourceManager.GetString("Task_DevResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Research II.
        /// </summary>
        public static string Task_DevResearchII {
            get {
                return ResourceManager.GetString("Task_DevResearchII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Research III.
        /// </summary>
        public static string Task_DevResearchIII {
            get {
                return ResourceManager.GetString("Task_DevResearchIII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Research IV.
        /// </summary>
        public static string Task_DevResearchIV {
            get {
                return ResourceManager.GetString("Task_DevResearchIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Research V.
        /// </summary>
        public static string Task_DevResearchV {
            get {
                return ResourceManager.GetString("Task_DevResearchV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize Development.
        /// </summary>
        public static string Task_FinalizeDev {
            get {
                return ResourceManager.GetString("Task_FinalizeDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Review and Launch.
        /// </summary>
        public static string Task_FinalReview {
            get {
                return ResourceManager.GetString("Task_FinalReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-end Development.
        /// </summary>
        public static string Task_FrontendDev {
            get {
                return ResourceManager.GetString("Task_FrontendDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-end Development II.
        /// </summary>
        public static string Task_FrontendDevII {
            get {
                return ResourceManager.GetString("Task_FrontendDevII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Review.
        /// </summary>
        public static string Task_ProjectReview {
            get {
                return ResourceManager.GetString("Task_ProjectReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stakeholder Interviews.
        /// </summary>
        public static string Task_StakeholderInterviews {
            get {
                return ResourceManager.GetString("Task_StakeholderInterviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Testing.
        /// </summary>
        public static string Task_UserTesting {
            get {
                return ResourceManager.GetString("Task_UserTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Testing and Fix Bugs.
        /// </summary>
        public static string Task_UserTestingFix {
            get {
                return ResourceManager.GetString("Task_UserTestingFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Testing and Fix Bugs II.
        /// </summary>
        public static string Task_UserTestingFixII {
            get {
                return ResourceManager.GetString("Task_UserTestingFixII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Design.
        /// </summary>
        public static string Task_VisualDesign {
            get {
                return ResourceManager.GetString("Task_VisualDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Design II.
        /// </summary>
        public static string Task_VisualDesignII {
            get {
                return ResourceManager.GetString("Task_VisualDesignII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframing.
        /// </summary>
        public static string Task_Wireframing {
            get {
                return ResourceManager.GetString("Task_Wireframing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WireFraming II.
        /// </summary>
        public static string Task_WireframingII {
            get {
                return ResourceManager.GetString("Task_WireframingII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Again to Confirm Add.
        /// </summary>
        public static string Team_Confirm {
            get {
                return ResourceManager.GetString("Team_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Team Members.
        /// </summary>
        public static string Team_Filter_All {
            get {
                return ResourceManager.GetString("Team_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Team_Filter_Dev {
            get {
                return ResourceManager.GetString("Team_Filter_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        public static string Team_Filter_PM {
            get {
                return ResourceManager.GetString("Team_Filter_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Experience.
        /// </summary>
        public static string Team_Filter_UX {
            get {
                return ResourceManager.GetString("Team_Filter_UX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Design.
        /// </summary>
        public static string Team_Filter_Visual {
            get {
                return ResourceManager.GetString("Team_Filter_Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs available.
        /// </summary>
        public static string Team_HrsAvailable {
            get {
                return ResourceManager.GetString("Team_HrsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string Team_Projects {
            get {
                return ResourceManager.GetString("Team_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Team Member To Add.
        /// </summary>
        public static string Team_TitleLabelSelect {
            get {
                return ResourceManager.GetString("Team_TitleLabelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Team Members.
        /// </summary>
        public static string Team_TitleLabelView {
            get {
                return ResourceManager.GetString("Team_TitleLabelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management Dashboard.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a production app, these links can be used to show assets located on external storage services such as Dropbox or point to another location within the site..
        /// </summary>
        public static string ViewLink_Alert_Msg {
            get {
                return ResourceManager.GetString("ViewLink_Alert_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Sample Application.
        /// </summary>
        public static string ViewLink_Alert_Title {
            get {
                return ResourceManager.GetString("ViewLink_Alert_Title", resourceCulture);
            }
        }
    }
}
